spring:
  application:
    name: ai-code-mother-backend
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/ai_code_mother}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:}
  # redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
      ttl: ${REDIS_TTL:3600}
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.carpe.aicodemother.controller
# knife4j
# 接口文档配置
knife4j:
  enable: true
  basic:
    enable: true
    username: root
    password: 123456
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: ${AI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
      api-key: ${AI_API_KEY:}
      model-name: ${AI_CHAT_MODEL:qwen3-coder-480b-a35b-instruct}
      #      strict-json-schema: true
      #      response-format: json_object
      max-tokens: 8192
      log-requests: true
      log-responses: true
      max-retries: 3
    streaming-chat-model:
      base-url: ${AI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
      api-key: ${AI_API_KEY:}
      model-name: ${AI_CHAT_MODEL:qwen3-coder-480b-a35b-instruct}
      max-tokens: 8192
      log-requests: true
      log-responses: true
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: ${AI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
      api-key: ${AI_API_KEY:}
      model-name: ${AI_REASONING_MODEL:qwen3-coder-plus-2025-07-22}
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: ${AI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
      api-key: ${AI_API_KEY:}
      model-name: ${AI_ROUTING_MODEL:qwen3-coder-480b-a35b-instruct}
      log-requests: true
      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: ${COS_HOST:}
    secretId: ${COS_SECRET_ID:}
    secretKey: ${COS_SECRET_KEY:}
    region: ${COS_REGION:}
    bucket: ${COS_BUCKET:}
# Pexels 图片搜索配置
pexels:
  api-key: ${PEXELS_API_KEY:}
# 阿里云 DashScope 配置
dashscope:
  api-key: ${DASHSCOPE_API_KEY:}
  image-model: ${DASHSCOPE_IMAGE_MODEL:}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

