spring:
  application:
    name: ai-code-mother-backend
server:
  port: 8123
  servlet:
    context-path: /api
# 配置 springdoc-openapi，用于生成 API 文档
springdoc:
  group-configs:                 # 启用分组功能（用于文档页面分栏显示）
    - group: 'default'           # 分组名称（你可以建多个）
      packages-to-scan: com.carpe.aicodemother.controller
      # 指定哪些包下的 Controller 参与文档生成
# Knife4j 的 UI 设置
knife4j:
  enable: true                   # 启用 Knife4j 增强 UI
  setting:
    language: zh_cn              # UI 语言设置为中文（zh_cn）